import * as mincut from 'imports/Ramparts';
import { RoomCollector } from './roomCollector';

export class autobuild {
	private static getBuildingsPosition(x: number, y: number): BunkerPositions {
		return {
			RCL: {
				'2': {
					road: {
						pos: [
							{ x: x, y: y - 1 },
							{ x: x - 1, y: y },
							{ x: x + 1, y: y },
							{ x: x + 2, y: y },
							{ x: x, y: y + 1 },
							{ x: x + 3, y: y + 1 },
						],
					},
					spawn: { pos: [{ x: x, y: y }] },
					extension: {
						pos: [
							{ x: x + 1, y: y + 1 },
							{ x: x + 2, y: y + 1 },
							{ x: x + 1, y: y + 2 },
							{ x: x + 2, y: y + 2 },
							{ x: x + 3, y: y + 2 },
						],
					},
				},
				'3': {
					road: {
						pos: [
							{ x: x + 3, y: y - 2 },
							{ x: x, y: y - 1 },
							{ x: x + 2, y: y - 1 },
							{ x: x - 1, y: y },
							{ x: x + 1, y: y },
							{ x: x + 2, y: y },
							{ x: x, y: y + 1 },
							{ x: x + 3, y: y + 1 },
							{ x: x + 4, y: y + 2 },
						],
					},
					extension: {
						pos: [
							{ x: x + 3, y: y - 1 },
							{ x: x + 4, y: y - 1 },
							{ x: x + 3, y: y },
							{ x: x + 4, y: y },
							{ x: x + 1, y: y + 1 },
							{ x: x + 2, y: y + 1 },
							{ x: x + 4, y: y + 1 },
							{ x: x + 1, y: y + 2 },
							{ x: x + 2, y: y + 2 },
							{ x: x + 3, y: y + 2 },
						],
					},
					spawn: { pos: [{ x: x, y: y }] },
					tower: { pos: [{ x: x + 5, y: y + 3 }] },
				},
				'4': {
					extension: {
						pos: [
							{ x: x + 4, y: y - 3 },
							{ x: x + 5, y: y - 3 },
							{ x: x + 3, y: y - 1 },
							{ x: x + 4, y: y - 1 },
							{ x: x + 5, y: y - 1 },
							{ x: x + 3, y: y },
							{ x: x + 4, y: y },
							{ x: x + 5, y: y },
							{ x: x + 1, y: y + 1 },
							{ x: x + 2, y: y + 1 },
							{ x: x + 4, y: y + 1 },
							{ x: x + 5, y: y + 1 },
							{ x: x + 1, y: y + 2 },
							{ x: x + 2, y: y + 2 },
							{ x: x + 3, y: y + 2 },
							{ x: x + 5, y: y + 2 },
							{ x: x + 1, y: y + 3 },
							{ x: x + 2, y: y + 3 },
							{ x: x + 3, y: y + 3 },
							{ x: x + 4, y: y + 3 },
						],
					},
					road: {
						pos: [
							{ x: x - 6, y: y - 8 },
							{ x: x - 5, y: y - 8 },
							{ x: x - 4, y: y - 8 },
							{ x: x - 3, y: y - 8 },
							{ x: x - 2, y: y - 8 },
							{ x: x - 1, y: y - 8 },
							{ x: x, y: y - 8 },
							{ x: x + 1, y: y - 8 },
							{ x: x + 2, y: y - 8 },
							{ x: x + 3, y: y - 8 },
							{ x: x + 4, y: y - 8 },
							{ x: x + 5, y: y - 8 },
							{ x: x + 6, y: y - 8 },
							{ x: x - 6, y: y - 7 },
							{ x: x, y: y - 7 },
							{ x: x + 6, y: y - 7 },
							{ x: x - 6, y: y - 6 },
							{ x: x - 4, y: y - 6 },
							{ x: x, y: y - 6 },
							{ x: x + 4, y: y - 6 },
							{ x: x + 6, y: y - 6 },
							{ x: x - 6, y: y - 5 },
							{ x: x - 3, y: y - 5 },
							{ x: x, y: y - 5 },
							{ x: x + 3, y: y - 5 },
							{ x: x + 6, y: y - 5 },
							{ x: x - 6, y: y - 4 },
							{ x: x - 2, y: y - 4 },
							{ x: x - 1, y: y - 4 },
							{ x: x + 1, y: y - 4 },
							{ x: x + 2, y: y - 4 },
							{ x: x + 6, y: y - 4 },
							{ x: x - 6, y: y - 3 },
							{ x: x - 2, y: y - 3 },
							{ x: x, y: y - 3 },
							{ x: x + 2, y: y - 3 },
							{ x: x + 6, y: y - 3 },
							{ x: x - 6, y: y - 2 },
							{ x: x - 5, y: y - 2 },
							{ x: x - 4, y: y - 2 },
							{ x: x - 3, y: y - 2 },
							{ x: x - 1, y: y - 2 },
							{ x: x + 1, y: y - 2 },
							{ x: x + 3, y: y - 2 },
							{ x: x + 4, y: y - 2 },
							{ x: x + 5, y: y - 2 },
							{ x: x + 6, y: y - 2 },
							{ x: x - 6, y: y - 1 },
							{ x: x - 2, y: y - 1 },
							{ x: x, y: y - 1 },
							{ x: x + 2, y: y - 1 },
							{ x: x + 6, y: y - 1 },
							{ x: x - 6, y: y },
							{ x: x - 2, y: y },
							{ x: x - 1, y: y },
							{ x: x + 1, y: y },
							{ x: x + 2, y: y },
							{ x: x + 6, y: y },
							{ x: x - 6, y: y + 1 },
							{ x: x - 3, y: y + 1 },
							{ x: x, y: y + 1 },
							{ x: x + 3, y: y + 1 },
							{ x: x + 6, y: y + 1 },
							{ x: x - 6, y: y + 2 },
							{ x: x - 4, y: y + 2 },
							{ x: x, y: y + 2 },
							{ x: x + 4, y: y + 2 },
							{ x: x + 6, y: y + 2 },
							{ x: x - 6, y: y + 3 },
							{ x: x, y: y + 3 },
							{ x: x + 6, y: y + 3 },
							{ x: x - 6, y: y + 4 },
							{ x: x - 5, y: y + 4 },
							{ x: x - 4, y: y + 4 },
							{ x: x - 3, y: y + 4 },
							{ x: x - 2, y: y + 4 },
							{ x: x - 1, y: y + 4 },
							{ x: x, y: y + 4 },
							{ x: x + 1, y: y + 4 },
							{ x: x + 2, y: y + 4 },
							{ x: x + 3, y: y + 4 },
							{ x: x + 4, y: y + 4 },
							{ x: x + 5, y: y + 4 },
							{ x: x + 6, y: y + 4 },
						],
					},
					storage: { pos: [{ x: x + 1, y: y - 1 }] },
					spawn: { pos: [{ x: x, y: y }] },
					tower: { pos: [{ x: x + 5, y: y + 3 }] },
				},
				'5': {
					extension: {
						pos: [
							{ x: x + 4, y: y - 7 },
							{ x: x + 2, y: y - 6 },
							{ x: x + 3, y: y - 6 },
							{ x: x + 5, y: y - 6 },
							{ x: x + 2, y: y - 5 },
							{ x: x + 4, y: y - 5 },
							{ x: x + 5, y: y - 5 },
							{ x: x + 3, y: y - 4 },
							{ x: x + 4, y: y - 4 },
							{ x: x + 5, y: y - 4 },
							{ x: x + 4, y: y - 3 },
							{ x: x + 5, y: y - 3 },
							{ x: x + 3, y: y - 1 },
							{ x: x + 4, y: y - 1 },
							{ x: x + 5, y: y - 1 },
							{ x: x + 3, y: y },
							{ x: x + 4, y: y },
							{ x: x + 5, y: y },
							{ x: x + 1, y: y + 1 },
							{ x: x + 2, y: y + 1 },
							{ x: x + 4, y: y + 1 },
							{ x: x + 5, y: y + 1 },
							{ x: x + 1, y: y + 2 },
							{ x: x + 2, y: y + 2 },
							{ x: x + 3, y: y + 2 },
							{ x: x + 5, y: y + 2 },
							{ x: x + 1, y: y + 3 },
							{ x: x + 2, y: y + 3 },
							{ x: x + 3, y: y + 3 },
							{ x: x + 4, y: y + 3 },
						],
					},
					road: {
						pos: [
							{ x: x - 6, y: y - 8 },
							{ x: x - 5, y: y - 8 },
							{ x: x - 4, y: y - 8 },
							{ x: x - 3, y: y - 8 },
							{ x: x - 2, y: y - 8 },
							{ x: x - 1, y: y - 8 },
							{ x: x, y: y - 8 },
							{ x: x + 1, y: y - 8 },
							{ x: x + 2, y: y - 8 },
							{ x: x + 3, y: y - 8 },
							{ x: x + 4, y: y - 8 },
							{ x: x + 5, y: y - 8 },
							{ x: x + 6, y: y - 8 },
							{ x: x - 6, y: y - 7 },
							{ x: x, y: y - 7 },
							{ x: x + 6, y: y - 7 },
							{ x: x - 6, y: y - 6 },
							{ x: x - 4, y: y - 6 },
							{ x: x, y: y - 6 },
							{ x: x + 4, y: y - 6 },
							{ x: x + 6, y: y - 6 },
							{ x: x - 6, y: y - 5 },
							{ x: x - 3, y: y - 5 },
							{ x: x, y: y - 5 },
							{ x: x + 3, y: y - 5 },
							{ x: x + 6, y: y - 5 },
							{ x: x - 6, y: y - 4 },
							{ x: x - 2, y: y - 4 },
							{ x: x - 1, y: y - 4 },
							{ x: x + 1, y: y - 4 },
							{ x: x + 2, y: y - 4 },
							{ x: x + 6, y: y - 4 },
							{ x: x - 6, y: y - 3 },
							{ x: x - 2, y: y - 3 },
							{ x: x, y: y - 3 },
							{ x: x + 2, y: y - 3 },
							{ x: x + 6, y: y - 3 },
							{ x: x - 6, y: y - 2 },
							{ x: x - 5, y: y - 2 },
							{ x: x - 4, y: y - 2 },
							{ x: x - 3, y: y - 2 },
							{ x: x - 1, y: y - 2 },
							{ x: x + 1, y: y - 2 },
							{ x: x + 3, y: y - 2 },
							{ x: x + 4, y: y - 2 },
							{ x: x + 5, y: y - 2 },
							{ x: x + 6, y: y - 2 },
							{ x: x - 6, y: y - 1 },
							{ x: x - 2, y: y - 1 },
							{ x: x, y: y - 1 },
							{ x: x + 2, y: y - 1 },
							{ x: x + 6, y: y - 1 },
							{ x: x - 6, y: y },
							{ x: x - 2, y: y },
							{ x: x - 1, y: y },
							{ x: x + 1, y: y },
							{ x: x + 2, y: y },
							{ x: x + 6, y: y },
							{ x: x - 6, y: y + 1 },
							{ x: x - 3, y: y + 1 },
							{ x: x, y: y + 1 },
							{ x: x + 3, y: y + 1 },
							{ x: x + 6, y: y + 1 },
							{ x: x - 6, y: y + 2 },
							{ x: x - 4, y: y + 2 },
							{ x: x, y: y + 2 },
							{ x: x + 4, y: y + 2 },
							{ x: x + 6, y: y + 2 },
							{ x: x - 6, y: y + 3 },
							{ x: x, y: y + 3 },
							{ x: x + 6, y: y + 3 },
							{ x: x - 6, y: y + 4 },
							{ x: x - 5, y: y + 4 },
							{ x: x - 4, y: y + 4 },
							{ x: x - 3, y: y + 4 },
							{ x: x - 2, y: y + 4 },
							{ x: x - 1, y: y + 4 },
							{ x: x, y: y + 4 },
							{ x: x + 1, y: y + 4 },
							{ x: x + 2, y: y + 4 },
							{ x: x + 3, y: y + 4 },
							{ x: x + 4, y: y + 4 },
							{ x: x + 5, y: y + 4 },
							{ x: x + 6, y: y + 4 },
						],
					},
					tower: {
						pos: [
							{ x: x + 3, y: y - 3 },
							{ x: x + 5, y: y + 3 },
						],
					},
					storage: { pos: [{ x: x + 1, y: y - 1 }] },
					spawn: { pos: [{ x: x, y: y }] },
				},
				'6': {
					road: {
						pos: [
							{ x: x - 6, y: y - 8 },
							{ x: x - 5, y: y - 8 },
							{ x: x - 4, y: y - 8 },
							{ x: x - 3, y: y - 8 },
							{ x: x - 2, y: y - 8 },
							{ x: x - 1, y: y - 8 },
							{ x: x, y: y - 8 },
							{ x: x + 1, y: y - 8 },
							{ x: x + 2, y: y - 8 },
							{ x: x + 3, y: y - 8 },
							{ x: x + 4, y: y - 8 },
							{ x: x + 5, y: y - 8 },
							{ x: x + 6, y: y - 8 },
							{ x: x - 6, y: y - 7 },
							{ x: x, y: y - 7 },
							{ x: x + 6, y: y - 7 },
							{ x: x - 6, y: y - 6 },
							{ x: x - 4, y: y - 6 },
							{ x: x, y: y - 6 },
							{ x: x + 4, y: y - 6 },
							{ x: x + 6, y: y - 6 },
							{ x: x - 6, y: y - 5 },
							{ x: x - 3, y: y - 5 },
							{ x: x, y: y - 5 },
							{ x: x + 3, y: y - 5 },
							{ x: x + 6, y: y - 5 },
							{ x: x - 6, y: y - 4 },
							{ x: x - 2, y: y - 4 },
							{ x: x - 1, y: y - 4 },
							{ x: x + 1, y: y - 4 },
							{ x: x + 2, y: y - 4 },
							{ x: x + 6, y: y - 4 },
							{ x: x - 6, y: y - 3 },
							{ x: x - 2, y: y - 3 },
							{ x: x, y: y - 3 },
							{ x: x + 2, y: y - 3 },
							{ x: x + 6, y: y - 3 },
							{ x: x - 6, y: y - 2 },
							{ x: x - 5, y: y - 2 },
							{ x: x - 4, y: y - 2 },
							{ x: x - 3, y: y - 2 },
							{ x: x - 1, y: y - 2 },
							{ x: x + 1, y: y - 2 },
							{ x: x + 3, y: y - 2 },
							{ x: x + 4, y: y - 2 },
							{ x: x + 5, y: y - 2 },
							{ x: x + 6, y: y - 2 },
							{ x: x - 6, y: y - 1 },
							{ x: x - 2, y: y - 1 },
							{ x: x, y: y - 1 },
							{ x: x + 2, y: y - 1 },
							{ x: x + 6, y: y - 1 },
							{ x: x - 6, y: y },
							{ x: x - 2, y: y },
							{ x: x - 1, y: y },
							{ x: x + 1, y: y },
							{ x: x + 2, y: y },
							{ x: x + 6, y: y },
							{ x: x - 6, y: y + 1 },
							{ x: x - 3, y: y + 1 },
							{ x: x, y: y + 1 },
							{ x: x + 3, y: y + 1 },
							{ x: x + 6, y: y + 1 },
							{ x: x - 6, y: y + 2 },
							{ x: x - 4, y: y + 2 },
							{ x: x, y: y + 2 },
							{ x: x + 4, y: y + 2 },
							{ x: x + 6, y: y + 2 },
							{ x: x - 6, y: y + 3 },
							{ x: x, y: y + 3 },
							{ x: x + 6, y: y + 3 },
							{ x: x - 6, y: y + 4 },
							{ x: x - 5, y: y + 4 },
							{ x: x - 4, y: y + 4 },
							{ x: x - 3, y: y + 4 },
							{ x: x - 2, y: y + 4 },
							{ x: x - 1, y: y + 4 },
							{ x: x, y: y + 4 },
							{ x: x + 1, y: y + 4 },
							{ x: x + 2, y: y + 4 },
							{ x: x + 3, y: y + 4 },
							{ x: x + 4, y: y + 4 },
							{ x: x + 5, y: y + 4 },
							{ x: x + 6, y: y + 4 },
						],
					},
					extension: {
						pos: [
							{ x: x - 2, y: y - 7 },
							{ x: x - 1, y: y - 7 },
							{ x: x + 1, y: y - 7 },
							{ x: x + 2, y: y - 7 },
							{ x: x + 3, y: y - 7 },
							{ x: x + 4, y: y - 7 },
							{ x: x - 1, y: y - 6 },
							{ x: x + 1, y: y - 6 },
							{ x: x + 2, y: y - 6 },
							{ x: x + 3, y: y - 6 },
							{ x: x + 5, y: y - 6 },
							{ x: x - 1, y: y - 5 },
							{ x: x + 1, y: y - 5 },
							{ x: x + 2, y: y - 5 },
							{ x: x + 4, y: y - 5 },
							{ x: x + 5, y: y - 5 },
							{ x: x + 3, y: y - 4 },
							{ x: x + 4, y: y - 4 },
							{ x: x + 5, y: y - 4 },
							{ x: x - 3, y: y - 3 },
							{ x: x + 4, y: y - 3 },
							{ x: x + 5, y: y - 3 },
							{ x: x + 3, y: y - 1 },
							{ x: x + 4, y: y - 1 },
							{ x: x + 5, y: y - 1 },
							{ x: x + 3, y: y },
							{ x: x + 4, y: y },
							{ x: x + 5, y: y },
							{ x: x + 1, y: y + 1 },
							{ x: x + 2, y: y + 1 },
							{ x: x + 4, y: y + 1 },
							{ x: x + 5, y: y + 1 },
							{ x: x + 1, y: y + 2 },
							{ x: x + 2, y: y + 2 },
							{ x: x + 3, y: y + 2 },
							{ x: x + 5, y: y + 2 },
							{ x: x + 1, y: y + 3 },
							{ x: x + 2, y: y + 3 },
							{ x: x + 3, y: y + 3 },
							{ x: x + 4, y: y + 3 },
						],
					},
					lab: {
						pos: [
							{ x: x - 3, y: y - 6 },
							{ x: x - 2, y: y - 6 },
							{ x: x - 2, y: y - 5 },
						],
					},
					tower: {
						pos: [
							{ x: x + 3, y: y - 3 },
							{ x: x + 5, y: y + 3 },
						],
					},
					container: { pos: [{ x: x, y: y - 2 }] },
					terminal: { pos: [{ x: x - 1, y: y - 1 }] },
					storage: { pos: [{ x: x + 1, y: y - 1 }] },
					spawn: { pos: [{ x: x, y: y }] },
				},
				'7': {
					road: {
						pos: [
							{ x: x - 6, y: y - 8 },
							{ x: x - 5, y: y - 8 },
							{ x: x - 4, y: y - 8 },
							{ x: x - 3, y: y - 8 },
							{ x: x - 2, y: y - 8 },
							{ x: x - 1, y: y - 8 },
							{ x: x, y: y - 8 },
							{ x: x + 1, y: y - 8 },
							{ x: x + 2, y: y - 8 },
							{ x: x + 3, y: y - 8 },
							{ x: x + 4, y: y - 8 },
							{ x: x + 5, y: y - 8 },
							{ x: x + 6, y: y - 8 },
							{ x: x - 6, y: y - 7 },
							{ x: x, y: y - 7 },
							{ x: x + 6, y: y - 7 },
							{ x: x - 6, y: y - 6 },
							{ x: x - 4, y: y - 6 },
							{ x: x, y: y - 6 },
							{ x: x + 4, y: y - 6 },
							{ x: x + 6, y: y - 6 },
							{ x: x - 6, y: y - 5 },
							{ x: x - 3, y: y - 5 },
							{ x: x, y: y - 5 },
							{ x: x + 3, y: y - 5 },
							{ x: x + 6, y: y - 5 },
							{ x: x - 6, y: y - 4 },
							{ x: x - 2, y: y - 4 },
							{ x: x - 1, y: y - 4 },
							{ x: x + 1, y: y - 4 },
							{ x: x + 2, y: y - 4 },
							{ x: x + 6, y: y - 4 },
							{ x: x - 6, y: y - 3 },
							{ x: x - 2, y: y - 3 },
							{ x: x, y: y - 3 },
							{ x: x + 2, y: y - 3 },
							{ x: x + 6, y: y - 3 },
							{ x: x - 6, y: y - 2 },
							{ x: x - 5, y: y - 2 },
							{ x: x - 4, y: y - 2 },
							{ x: x - 3, y: y - 2 },
							{ x: x - 1, y: y - 2 },
							{ x: x + 1, y: y - 2 },
							{ x: x + 3, y: y - 2 },
							{ x: x + 4, y: y - 2 },
							{ x: x + 5, y: y - 2 },
							{ x: x + 6, y: y - 2 },
							{ x: x - 6, y: y - 1 },
							{ x: x - 2, y: y - 1 },
							{ x: x, y: y - 1 },
							{ x: x + 2, y: y - 1 },
							{ x: x + 6, y: y - 1 },
							{ x: x - 6, y: y },
							{ x: x - 2, y: y },
							{ x: x - 1, y: y },
							{ x: x + 1, y: y },
							{ x: x + 2, y: y },
							{ x: x + 6, y: y },
							{ x: x - 6, y: y + 1 },
							{ x: x - 3, y: y + 1 },
							{ x: x, y: y + 1 },
							{ x: x + 3, y: y + 1 },
							{ x: x + 6, y: y + 1 },
							{ x: x - 6, y: y + 2 },
							{ x: x - 4, y: y + 2 },
							{ x: x, y: y + 2 },
							{ x: x + 4, y: y + 2 },
							{ x: x + 6, y: y + 2 },
							{ x: x - 6, y: y + 3 },
							{ x: x, y: y + 3 },
							{ x: x + 6, y: y + 3 },
							{ x: x - 6, y: y + 4 },
							{ x: x - 5, y: y + 4 },
							{ x: x - 4, y: y + 4 },
							{ x: x - 3, y: y + 4 },
							{ x: x - 2, y: y + 4 },
							{ x: x - 1, y: y + 4 },
							{ x: x, y: y + 4 },
							{ x: x + 1, y: y + 4 },
							{ x: x + 2, y: y + 4 },
							{ x: x + 3, y: y + 4 },
							{ x: x + 4, y: y + 4 },
							{ x: x + 5, y: y + 4 },
							{ x: x + 6, y: y + 4 },
						],
					},
					tower: {
						pos: [
							{ x: x - 5, y: y - 7 },
							{ x: x + 3, y: y - 3 },
							{ x: x + 5, y: y + 3 },
						],
					},
					extension: {
						pos: [
							{ x: x - 2, y: y - 7 },
							{ x: x - 1, y: y - 7 },
							{ x: x + 1, y: y - 7 },
							{ x: x + 2, y: y - 7 },
							{ x: x + 3, y: y - 7 },
							{ x: x + 4, y: y - 7 },
							{ x: x - 1, y: y - 6 },
							{ x: x + 1, y: y - 6 },
							{ x: x + 2, y: y - 6 },
							{ x: x + 3, y: y - 6 },
							{ x: x + 5, y: y - 6 },
							{ x: x - 1, y: y - 5 },
							{ x: x + 1, y: y - 5 },
							{ x: x + 2, y: y - 5 },
							{ x: x + 4, y: y - 5 },
							{ x: x + 5, y: y - 5 },
							{ x: x + 3, y: y - 4 },
							{ x: x + 4, y: y - 4 },
							{ x: x + 5, y: y - 4 },
							{ x: x - 4, y: y - 3 },
							{ x: x - 3, y: y - 3 },
							{ x: x + 4, y: y - 3 },
							{ x: x + 5, y: y - 3 },
							{ x: x + 3, y: y - 1 },
							{ x: x + 4, y: y - 1 },
							{ x: x + 5, y: y - 1 },
							{ x: x + 3, y: y },
							{ x: x + 4, y: y },
							{ x: x + 5, y: y },
							{ x: x - 2, y: y + 1 },
							{ x: x - 1, y: y + 1 },
							{ x: x + 1, y: y + 1 },
							{ x: x + 2, y: y + 1 },
							{ x: x + 4, y: y + 1 },
							{ x: x + 5, y: y + 1 },
							{ x: x - 3, y: y + 2 },
							{ x: x - 2, y: y + 2 },
							{ x: x - 1, y: y + 2 },
							{ x: x + 1, y: y + 2 },
							{ x: x + 2, y: y + 2 },
							{ x: x + 3, y: y + 2 },
							{ x: x + 5, y: y + 2 },
							{ x: x - 4, y: y + 3 },
							{ x: x - 3, y: y + 3 },
							{ x: x - 2, y: y + 3 },
							{ x: x - 1, y: y + 3 },
							{ x: x + 1, y: y + 3 },
							{ x: x + 2, y: y + 3 },
							{ x: x + 3, y: y + 3 },
							{ x: x + 4, y: y + 3 },
						],
					},
					lab: {
						pos: [
							{ x: x - 3, y: y - 6 },
							{ x: x - 2, y: y - 6 },
							{ x: x - 4, y: y - 5 },
							{ x: x - 2, y: y - 5 },
							{ x: x - 4, y: y - 4 },
							{ x: x - 3, y: y - 4 },
						],
					},
					container: { pos: [{ x: x, y: y - 2 }] },
					spawn: {
						pos: [
							{ x: x + 2, y: y - 2 },
							{ x: x, y: y },
						],
					},
					terminal: { pos: [{ x: x - 1, y: y - 1 }] },
					storage: { pos: [{ x: x + 1, y: y - 1 }] },
				},
				'8': {
					road: {
						pos: [
							{ x: x - 6, y: y - 8 },
							{ x: x - 5, y: y - 8 },
							{ x: x - 4, y: y - 8 },
							{ x: x - 3, y: y - 8 },
							{ x: x - 2, y: y - 8 },
							{ x: x - 1, y: y - 8 },
							{ x: x, y: y - 8 },
							{ x: x + 1, y: y - 8 },
							{ x: x + 2, y: y - 8 },
							{ x: x + 3, y: y - 8 },
							{ x: x + 4, y: y - 8 },
							{ x: x + 5, y: y - 8 },
							{ x: x + 6, y: y - 8 },
							{ x: x - 6, y: y - 7 },
							{ x: x, y: y - 7 },
							{ x: x + 6, y: y - 7 },
							{ x: x - 6, y: y - 6 },
							{ x: x - 4, y: y - 6 },
							{ x: x, y: y - 6 },
							{ x: x + 4, y: y - 6 },
							{ x: x + 6, y: y - 6 },
							{ x: x - 6, y: y - 5 },
							{ x: x - 3, y: y - 5 },
							{ x: x, y: y - 5 },
							{ x: x + 3, y: y - 5 },
							{ x: x + 6, y: y - 5 },
							{ x: x - 6, y: y - 4 },
							{ x: x - 2, y: y - 4 },
							{ x: x - 1, y: y - 4 },
							{ x: x + 1, y: y - 4 },
							{ x: x + 2, y: y - 4 },
							{ x: x + 6, y: y - 4 },
							{ x: x - 6, y: y - 3 },
							{ x: x - 2, y: y - 3 },
							{ x: x, y: y - 3 },
							{ x: x + 2, y: y - 3 },
							{ x: x + 6, y: y - 3 },
							{ x: x - 6, y: y - 2 },
							{ x: x - 5, y: y - 2 },
							{ x: x - 4, y: y - 2 },
							{ x: x - 3, y: y - 2 },
							{ x: x - 1, y: y - 2 },
							{ x: x + 1, y: y - 2 },
							{ x: x + 3, y: y - 2 },
							{ x: x + 4, y: y - 2 },
							{ x: x + 5, y: y - 2 },
							{ x: x + 6, y: y - 2 },
							{ x: x - 6, y: y - 1 },
							{ x: x - 2, y: y - 1 },
							{ x: x, y: y - 1 },
							{ x: x + 2, y: y - 1 },
							{ x: x + 6, y: y - 1 },
							{ x: x - 6, y: y },
							{ x: x - 2, y: y },
							{ x: x - 1, y: y },
							{ x: x + 1, y: y },
							{ x: x + 2, y: y },
							{ x: x + 6, y: y },
							{ x: x - 6, y: y + 1 },
							{ x: x - 3, y: y + 1 },
							{ x: x, y: y + 1 },
							{ x: x + 3, y: y + 1 },
							{ x: x + 6, y: y + 1 },
							{ x: x - 6, y: y + 2 },
							{ x: x - 4, y: y + 2 },
							{ x: x, y: y + 2 },
							{ x: x + 4, y: y + 2 },
							{ x: x + 6, y: y + 2 },
							{ x: x - 6, y: y + 3 },
							{ x: x, y: y + 3 },
							{ x: x + 6, y: y + 3 },
							{ x: x - 6, y: y + 4 },
							{ x: x - 5, y: y + 4 },
							{ x: x - 4, y: y + 4 },
							{ x: x - 3, y: y + 4 },
							{ x: x - 2, y: y + 4 },
							{ x: x - 1, y: y + 4 },
							{ x: x, y: y + 4 },
							{ x: x + 1, y: y + 4 },
							{ x: x + 2, y: y + 4 },
							{ x: x + 3, y: y + 4 },
							{ x: x + 4, y: y + 4 },
							{ x: x + 5, y: y + 4 },
							{ x: x + 6, y: y + 4 },
						],
					},
					tower: {
						pos: [
							{ x: x - 5, y: y - 7 },
							{ x: x + 5, y: y - 7 },
							{ x: x + 3, y: y - 3 },
							{ x: x - 3, y: y - 1 },
							{ x: x - 5, y: y + 3 },
							{ x: x + 5, y: y + 3 },
						],
					},
					lab: {
						pos: [
							{ x: x - 4, y: y - 7 },
							{ x: x - 3, y: y - 7 },
							{ x: x - 5, y: y - 6 },
							{ x: x - 3, y: y - 6 },
							{ x: x - 2, y: y - 6 },
							{ x: x - 5, y: y - 5 },
							{ x: x - 4, y: y - 5 },
							{ x: x - 2, y: y - 5 },
							{ x: x - 4, y: y - 4 },
							{ x: x - 3, y: y - 4 },
						],
					},
					extension: {
						pos: [
							{ x: x - 2, y: y - 7 },
							{ x: x - 1, y: y - 7 },
							{ x: x + 1, y: y - 7 },
							{ x: x + 2, y: y - 7 },
							{ x: x + 3, y: y - 7 },
							{ x: x + 4, y: y - 7 },
							{ x: x - 1, y: y - 6 },
							{ x: x + 1, y: y - 6 },
							{ x: x + 2, y: y - 6 },
							{ x: x + 3, y: y - 6 },
							{ x: x + 5, y: y - 6 },
							{ x: x - 1, y: y - 5 },
							{ x: x + 1, y: y - 5 },
							{ x: x + 2, y: y - 5 },
							{ x: x + 4, y: y - 5 },
							{ x: x + 5, y: y - 5 },
							{ x: x - 5, y: y - 4 },
							{ x: x + 3, y: y - 4 },
							{ x: x + 4, y: y - 4 },
							{ x: x + 5, y: y - 4 },
							{ x: x - 5, y: y - 3 },
							{ x: x - 4, y: y - 3 },
							{ x: x - 3, y: y - 3 },
							{ x: x + 4, y: y - 3 },
							{ x: x + 5, y: y - 3 },
							{ x: x - 5, y: y - 1 },
							{ x: x - 4, y: y - 1 },
							{ x: x + 3, y: y - 1 },
							{ x: x + 4, y: y - 1 },
							{ x: x + 5, y: y - 1 },
							{ x: x - 5, y: y },
							{ x: x - 4, y: y },
							{ x: x - 3, y: y },
							{ x: x + 3, y: y },
							{ x: x + 4, y: y },
							{ x: x + 5, y: y },
							{ x: x - 5, y: y + 1 },
							{ x: x - 4, y: y + 1 },
							{ x: x - 2, y: y + 1 },
							{ x: x - 1, y: y + 1 },
							{ x: x + 1, y: y + 1 },
							{ x: x + 2, y: y + 1 },
							{ x: x + 4, y: y + 1 },
							{ x: x + 5, y: y + 1 },
							{ x: x - 5, y: y + 2 },
							{ x: x - 3, y: y + 2 },
							{ x: x - 2, y: y + 2 },
							{ x: x - 1, y: y + 2 },
							{ x: x + 1, y: y + 2 },
							{ x: x + 2, y: y + 2 },
							{ x: x + 3, y: y + 2 },
							{ x: x + 5, y: y + 2 },
							{ x: x - 4, y: y + 3 },
							{ x: x - 3, y: y + 3 },
							{ x: x - 2, y: y + 3 },
							{ x: x - 1, y: y + 3 },
							{ x: x + 1, y: y + 3 },
							{ x: x + 2, y: y + 3 },
							{ x: x + 3, y: y + 3 },
							{ x: x + 4, y: y + 3 },
						],
					},
					spawn: {
						pos: [
							{ x: x, y: y - 4 },
							{ x: x + 2, y: y - 2 },
							{ x: x, y: y },
						],
					},
					nuker: { pos: [{ x: x - 1, y: y - 3 }] },
					observer: { pos: [{ x: x + 1, y: y - 3 }] },
					powerSpawn: { pos: [{ x: x - 2, y: y - 2 }] },
					container: { pos: [{ x: x, y: y - 2 }] },
					terminal: { pos: [{ x: x - 1, y: y - 1 }] },
					storage: { pos: [{ x: x + 1, y: y - 1 }] },
				},
			},
			rampart: {
				pos: [
					{ x: x - 6, y: y - 8 },
					{ x: x - 5, y: y - 8 },
					{ x: x - 4, y: y - 8 },
					{ x: x - 3, y: y - 8 },
					{ x: x - 2, y: y - 8 },
					{ x: x - 1, y: y - 8 },
					{ x: x, y: y - 8 },
					{ x: x + 1, y: y - 8 },
					{ x: x + 2, y: y - 8 },
					{ x: x + 3, y: y - 8 },
					{ x: x + 4, y: y - 8 },
					{ x: x + 5, y: y - 8 },
					{ x: x + 6, y: y - 8 },
					{ x: x - 6, y: y - 7 },
					{ x: x - 5, y: y - 7 },
					{ x: x - 4, y: y - 7 },
					{ x: x - 3, y: y - 7 },
					{ x: x - 2, y: y - 7 },
					{ x: x - 1, y: y - 7 },
					{ x: x, y: y - 7 },
					{ x: x + 1, y: y - 7 },
					{ x: x + 2, y: y - 7 },
					{ x: x + 3, y: y - 7 },
					{ x: x + 4, y: y - 7 },
					{ x: x + 5, y: y - 7 },
					{ x: x + 6, y: y - 7 },
					{ x: x - 6, y: y - 6 },
					{ x: x - 5, y: y - 6 },
					{ x: x - 4, y: y - 6 },
					{ x: x - 3, y: y - 6 },
					{ x: x - 2, y: y - 6 },
					{ x: x - 1, y: y - 6 },
					{ x: x, y: y - 6 },
					{ x: x + 1, y: y - 6 },
					{ x: x + 2, y: y - 6 },
					{ x: x + 3, y: y - 6 },
					{ x: x + 4, y: y - 6 },
					{ x: x + 5, y: y - 6 },
					{ x: x + 6, y: y - 6 },
					{ x: x - 6, y: y - 5 },
					{ x: x - 5, y: y - 5 },
					{ x: x - 4, y: y - 5 },
					{ x: x - 3, y: y - 5 },
					{ x: x - 2, y: y - 5 },
					{ x: x - 1, y: y - 5 },
					{ x: x, y: y - 5 },
					{ x: x + 1, y: y - 5 },
					{ x: x + 2, y: y - 5 },
					{ x: x + 3, y: y - 5 },
					{ x: x + 4, y: y - 5 },
					{ x: x + 5, y: y - 5 },
					{ x: x + 6, y: y - 5 },
					{ x: x - 6, y: y - 4 },
					{ x: x - 5, y: y - 4 },
					{ x: x - 4, y: y - 4 },
					{ x: x - 3, y: y - 4 },
					{ x: x - 2, y: y - 4 },
					{ x: x - 1, y: y - 4 },
					{ x: x, y: y - 4 },
					{ x: x + 1, y: y - 4 },
					{ x: x + 2, y: y - 4 },
					{ x: x + 3, y: y - 4 },
					{ x: x + 4, y: y - 4 },
					{ x: x + 5, y: y - 4 },
					{ x: x + 6, y: y - 4 },
					{ x: x - 6, y: y - 3 },
					{ x: x - 5, y: y - 3 },
					{ x: x - 4, y: y - 3 },
					{ x: x - 3, y: y - 3 },
					{ x: x - 2, y: y - 3 },
					{ x: x - 1, y: y - 3 },
					{ x: x, y: y - 3 },
					{ x: x + 1, y: y - 3 },
					{ x: x + 2, y: y - 3 },
					{ x: x + 3, y: y - 3 },
					{ x: x + 4, y: y - 3 },
					{ x: x + 5, y: y - 3 },
					{ x: x + 6, y: y - 3 },
					{ x: x - 6, y: y - 2 },
					{ x: x - 5, y: y - 2 },
					{ x: x - 4, y: y - 2 },
					{ x: x - 3, y: y - 2 },
					{ x: x - 2, y: y - 2 },
					{ x: x - 1, y: y - 2 },
					{ x: x, y: y - 2 },
					{ x: x + 1, y: y - 2 },
					{ x: x + 2, y: y - 2 },
					{ x: x + 3, y: y - 2 },
					{ x: x + 4, y: y - 2 },
					{ x: x + 5, y: y - 2 },
					{ x: x + 6, y: y - 2 },
					{ x: x - 6, y: y - 1 },
					{ x: x - 5, y: y - 1 },
					{ x: x - 4, y: y - 1 },
					{ x: x - 3, y: y - 1 },
					{ x: x - 2, y: y - 1 },
					{ x: x - 1, y: y - 1 },
					{ x: x, y: y - 1 },
					{ x: x + 1, y: y - 1 },
					{ x: x + 2, y: y - 1 },
					{ x: x + 3, y: y - 1 },
					{ x: x + 4, y: y - 1 },
					{ x: x + 5, y: y - 1 },
					{ x: x + 6, y: y - 1 },
					{ x: x - 6, y: y },
					{ x: x - 5, y: y },
					{ x: x - 4, y: y },
					{ x: x - 3, y: y },
					{ x: x - 2, y: y },
					{ x: x - 1, y: y },
					{ x: x, y: y },
					{ x: x + 1, y: y },
					{ x: x + 2, y: y },
					{ x: x + 3, y: y },
					{ x: x + 4, y: y },
					{ x: x + 5, y: y },
					{ x: x + 6, y: y },
					{ x: x - 6, y: y + 1 },
					{ x: x - 5, y: y + 1 },
					{ x: x - 4, y: y + 1 },
					{ x: x - 3, y: y + 1 },
					{ x: x - 2, y: y + 1 },
					{ x: x - 1, y: y + 1 },
					{ x: x, y: y + 1 },
					{ x: x + 1, y: y + 1 },
					{ x: x + 2, y: y + 1 },
					{ x: x + 3, y: y + 1 },
					{ x: x + 4, y: y + 1 },
					{ x: x + 5, y: y + 1 },
					{ x: x + 6, y: y + 1 },
					{ x: x - 6, y: y + 2 },
					{ x: x - 5, y: y + 2 },
					{ x: x - 4, y: y + 2 },
					{ x: x - 3, y: y + 2 },
					{ x: x - 2, y: y + 2 },
					{ x: x - 1, y: y + 2 },
					{ x: x, y: y + 2 },
					{ x: x + 1, y: y + 2 },
					{ x: x + 2, y: y + 2 },
					{ x: x + 3, y: y + 2 },
					{ x: x + 4, y: y + 2 },
					{ x: x + 5, y: y + 2 },
					{ x: x + 6, y: y + 2 },
					{ x: x - 6, y: y + 3 },
					{ x: x - 5, y: y + 3 },
					{ x: x - 4, y: y + 3 },
					{ x: x - 3, y: y + 3 },
					{ x: x - 2, y: y + 3 },
					{ x: x - 1, y: y + 3 },
					{ x: x, y: y + 3 },
					{ x: x + 1, y: y + 3 },
					{ x: x + 2, y: y + 3 },
					{ x: x + 3, y: y + 3 },
					{ x: x + 4, y: y + 3 },
					{ x: x + 5, y: y + 3 },
					{ x: x + 6, y: y + 3 },
					{ x: x - 6, y: y + 4 },
					{ x: x - 5, y: y + 4 },
					{ x: x - 4, y: y + 4 },
					{ x: x - 3, y: y + 4 },
					{ x: x - 2, y: y + 4 },
					{ x: x - 1, y: y + 4 },
					{ x: x, y: y + 4 },
					{ x: x + 1, y: y + 4 },
					{ x: x + 2, y: y + 4 },
					{ x: x + 3, y: y + 4 },
					{ x: x + 4, y: y + 4 },
					{ x: x + 5, y: y + 4 },
					{ x: x + 6, y: y + 4 },
				],
			},
		};
	}

	private static checkStructures(room: Room, amountStructures: AmountStructures) {
		const structures = RoomCollector.info[room.name];
		
		let spawnsState;
		let extensionsState;
		let towersState;
		let storageState;
		let terminalState;
		let containerState;

		if (amountStructures.spawns) {
			const spawns = structures.allStructures.filter(s => s.structureType === 'spawn');
			if (spawns.length < amountStructures.spawns) spawnsState = false;
			else spawnsState = true;
		} else spawnsState = true;

		if (amountStructures.extensions) {
			const extensions = structures.allStructures.filter(s => s.structureType === 'extension');
			if (extensions.length < amountStructures.extensions) extensionsState = false;
			else extensionsState = true;
		} else extensionsState = true;

		if (amountStructures.towers) {
			const towers = structures.allStructures.filter(s => s.structureType === 'tower');
			if (towers.length < amountStructures.towers) towersState = false;
			else towersState = true;
		} else towersState = true;

		if (amountStructures.storage) {
			if (!room.storage) storageState = false;
			else storageState = true;
		} else storageState = true;

		if (amountStructures.terminal) {
			if (!room.terminal) terminalState = false;
			else terminalState = true;
		} else terminalState = true;

		//if (basicStructures.container) {
		//    if (!room.terminal) terminalState = false;
		//    else terminalState = true;
		//} else terminalState = true;

		if (
			!spawnsState ||
			!extensionsState ||
			!towersState ||
			!storageState ||
			!terminalState ||
			!containerState
		) {
			this.run(room);
		}
	}

	/**
	 * @param {Object} room
	 */
	public static runBuild(room: Room) {
		if (room.controller!.level >= 2) {
			if (Game.time%51 === 50) mincut.util_mincut.test(room.name);
		}
		switch (room.controller!.level) {
			case 2:
				if (Game.time % 21 === 20) {
					const basicStructures = {
						spawns: 1,
						extensions: 5,
					};
					this.checkStructures(room, basicStructures);
				}
				break;
			case 3:
				if (Game.time % 21 === 20) {
					const basicStructures = {
						spawns: 1,
						extensions: 10,
						towers: 1,
					};
					this.checkStructures(room, basicStructures);
				}
				break;
			case 4:
				if (Game.time % 21 === 20) {
					const basicStructures = {
						spawns: 1,
						extensions: 20,
						towers: 1,
						storage: 1,
					};
					this.checkStructures(room, basicStructures);
				}
				break;
			case 5:
				if (Game.time % 21 === 20) {
					const basicStructures = {
						spawns: 1,
						extensions: 30,
						towers: 2,
						storage: 1,
					};
					this.checkStructures(room, basicStructures);
				}
				break;
			case 6:
				if (Game.time % 21 === 20) {
					const basicStructures = {
						spawns: 1,
						extensions: 40,
						towers: 2,
						storage: 1,
						terminal: 1,
						lab: 3,
						container: 1,
						extractor: 1,
					};
					this.checkStructures(room, basicStructures);
				}
				break;
			case 7:
				if (Game.time % 21 === 20) {
					const basicStructures = {
						spawns: 2,
						extensions: 50,
						towers: 3,
						storage: 1,
						terminal: 1,
						lab: 6,
						container: 1,
						extractor: 1,
					};
					this.checkStructures(room, basicStructures);
				}
				break;
			case 8:
				if (Game.time % 21 === 20) {
					const basicStructures = {
						spawns: 3,
						extensions: 60,
						towers: 6,
						storage: 1,
						terminal: 1,
						lab: 10,
						container: 1,
						extractor: 1,
						observer: 1,
						powerSpawn: 1,
						nuker: 1,
					};
					this.checkStructures(room, basicStructures);
				}
				break;
		}
	}

	private static createConstructions(
		room: Room,
		structures: {
			[name: string]: {
				pos: { x: number; y: number }[];
			};
		}
	) {
		for (let i in structures) {
			for (let j in structures[i].pos) {
				// @ts-ignore
				room.createConstructionSite(structures[i].pos[j].x, structures[i].pos[j].y, i);
			}
		}
	}

	private static run(room: Room) {
		const mySpawns = room.find(FIND_MY_SPAWNS);

		const x = mySpawns[0].pos.x;
		const y = mySpawns[0].pos.y;

		const source = room.find(FIND_SOURCES);
		const path1 = PathFinder.search(mySpawns[0].pos, { pos: source[0].pos, range: 1 });
		const path2 = PathFinder.search(mySpawns[0].pos, { pos: source[1].pos, range: 1 });
		const containers = [path1.path[path1.path.length - 1], path2.path[path2.path.length - 1]];

		const buildingsPosition = this.getBuildingsPosition(x, y).RCL[room.controller!.level];
		this.createConstructions(room, buildingsPosition);

		_.forEach(containers, c => {
			room.createConstructionSite(c, STRUCTURE_CONTAINER);
		})

		/* _.forEach(path1.path, c => {
			console.log(c);
			room.createConstructionSite(c, STRUCTURE_ROAD);
		})

		_.forEach(path2.path, c => {
			room.createConstructionSite(c, STRUCTURE_ROAD);
		}) */
	}
}
